### PR TITLE
coupon string

### PR DESCRIPTION
**Pull request by FnrDev**

### CODE REVIEW

**Comment by Dramex** [comment]
Coupon code
Invalid coupon code
Apply

**Comment by FnrDev** [comment]
> Coupon code Invalid coupon code Apply

Add these strings?

**Comment by Dramex** [comment]
> > Coupon code Invalid coupon code Apply
> 
> 
> 
> Add these strings?

Yes if they are not already exist

**Comment by FnrDev** [comment]
> > > Coupon code Invalid coupon code Apply
> > 
> > 
> > Add these strings?
> 
> Yes if they are not already exist

done 711aa093f85bbe7e95a9d426e6799e741f1b5f5d

**Comment by FnrDev** [comment]
> can you edit the key to "apply"

done

**Pull request merged**
