### PR TITLE
refactor: remove buy & use from one string

### PR DESCRIPTION
**Pull request by FnrDev**

### CODE REVIEW

**Comment by Dramex** [comment]
why the removal i think there should be two strings
"Buy & Use"
"Use"

since it can be translated to
اشتر واستخدم
بدلا من اشتر & استخدم

**Comment by FnrDev** [comment]
> why the removal i think there should be two strings "Buy & Use" "Use"
> 
> since it can be translated to اشتر واستخدم بدلا من اشتر & استخدم

@Alaa-Hijazi7  asked for these changes

**Comment by Dramex** [comment]
> > why the removal i think there should be two strings "Buy & Use" "Use"
> > since it can be translated to اشتر واستخدم بدلا من اشتر & استخدم
> 
> @Alaa-Hijazi7 asked for these changes

we refuse this change

**Comment by FnrDev** [comment]
> > > why the removal i think there should be two strings "Buy & Use" "Use"
> > > since it can be translated to اشتر واستخدم بدلا من اشتر & استخدم
> > 
> > 
> > @Alaa-Hijazi7 asked for these changes
> 
> we refuse this change

Ok i'll add `Buy & Use`, `Use` string

**Comment by Dramex** [comment]
> > > > why the removal i think there should be two strings "Buy & Use" "Use"
> > > > since it can be translated to اشتر واستخدم بدلا من اشتر & استخدم
> > > 
> > > 
> > > @Alaa-Hijazi7 asked for these changes
> > 
> > 
> > we refuse this change
> 
> Ok i'll add `Buy & Use`, `Use` string

Thanks

**Pull request merged**
